version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/locallink/frontend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/locallink/backend-node"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/locallink/backend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
